### ISSUE TITLE
Style Homepage Heading

### ISSUE THREAD

**Issue by dionysia-lemonaki** [dionysia-lemonaki/test#1]
Our client homepage needs styling.

## Tasks

- [ ]  Heading should have bold text
- [ ]  Heading text colour should be black
- [ ]  Heading should have a background shadow that stands out

**Comment by dionysia-lemonaki** [comment]
Meged
